### ISSUE TITLE
[Feature] Tune down silver generation, as it is super common

### ISSUE THREAD

**Issue by masuteri** [HPK-dev/YetJustAnotherSilver#3]
Given silver is mainly only used to make electrum in crafts and additions, and in other mods, it doesn't see much use otherwise, I would recommend tuning down silver generation a lot
![kuva](https://github.com/user-attachments/assets/7eac8cb0-0e28-438b-a0ef-f5e8a4568ad9)
The result after mining at Y 30 with a 4x8 drill for around 2k blocks

**Comment by eartzh** [comment]
Thanks for your report. ❤️ Please update your mod. 😄
https://modrinth.com/mod/yetjustanothersilver/version/1.0.3
