### ISSUE TITLE
[Feature] Optionally add Nether Silver Ore generation

### ISSUE THREAD

**Issue by vivvyinks** [HPK-dev/YetJustAnotherSilver#4]
Our server has run into the exact same problem that this mod solves, except... we've already finished worldgen. Is there any chance that nether silver could be added, so we can avoid regenerating the overworld and simply regen the nether?

**Comment by iceice666** [comment]
Why not open a portal in the Nether to travel long distances?   
Btw, our server's solution to this situation was to delete chunks that we hadn't built on.

**Comment by iceice666** [comment]
no updates, close.
